# -*- coding: utf-8 -*-
"""Copie de Data science notebook PART 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12te8SRZEfsoB2wuwqzyQtUPTaiLSDYSL

I) Extraction from the web of biographies (Text) for people belonging to two distinct categories (e.g., 1 You should ensure that you have at
Wikipedia biographies for Sculptors vs Computer Scientists)
"""

#to run just once
!pip install wikipedia
import wikipedia

"""II) Returns the two sets
of texts together with their classes
"""



"""II stores each (text, category)
pair in a pandas dataframe and stores each text into a file with
filename person_category.txt (e.g., FernadoBotero_Sculptor.txt), RajReddy_ComputerScientist.txt)

II  json file that holds the
KG Graph for each person (which you can easily map back to each
person).

https://drive.google.com/drive/folders/1Pzsg7XefE2n-9ylxDk4M5KOmnwXK_UkH?usp=drive_link
"""